version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
      java: corretto11
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - echo Build started on `date`
      - echo Building java
      - cd pensioner-detail-microservice
      - mvn clean package
      - echo Building the docker image
      - docker build -t pensioner-detail-microservice .
      - docker tag pensioner-detail-microservice:latest 156962844638.dkr.ecr.us-east-1.amazonaws.com/pension_system_repository-768656:pensioner-detail-microservice
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push 156962844638.dkr.ecr.us-east-1.amazonaws.com/pension_system_repository-768656:pensioner-detail-microservice
      - echo Writing definition files
      - printf '[{"name":"ij028-pensioner-detail-microservice-container","imageUri":"%s"}]' 156962844638.dkr.ecr.us-east-1.amazonaws.com/pension_system_repository-768656:pensioner-detail-microservice > taskdefinition.json

artifacts:
  files: pensioner-detail-microservice/taskdefinition.json
